config/routes.rb
Rails.application.routes.draw do
  resources :texters
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/texter.rb
class Texter < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/texters_controller.rb
class TextersController < ApplicationController
  before_action :set_texter, only: [:show, :edit, :update, :destroy]

  # GET /texters
  # GET /texters.json
  def index
    @texters = Texter.all
  end

  # GET /texters/1
  # GET /texters/1.json
  def show
  end

  # GET /texters/new
  def new
    @texter = Texter.new
  end

  # GET /texters/1/edit
  def edit
  end

  # POST /texters
  # POST /texters.json
  def create
    @texter = Texter.new(texter_params)
    
    respond_to do |format|
      if @texter.save
        message = "The message sent '#{@texter.client_name}' was just added."
        TwilioTextMessenger.new(message).call
        format.html { redirect_to @texter, notice: 'Texter was successfully created.' }
        format.json { render :show, status: :created, location: @texter }
      else
        format.html { render :new }
        format.json { render json: @texter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /texters/1
  # PATCH/PUT /texters/1.json
  def update
    respond_to do |format|
      if @texter.update(texter_params)
        format.html { redirect_to @texter, notice: 'Texter was successfully updated.' }
        format.json { render :show, status: :ok, location: @texter }
      else
        format.html { render :edit }
        format.json { render json: @texter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /texters/1
  # DELETE /texters/1.json
  def destroy
    @texter.destroy
    respond_to do |format|
      format.html { redirect_to texters_url, notice: 'Texter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_texter
      @texter = Texter.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def texter_params
      params.require(:texter).permit(:client_name, :message_description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/texters_helper.rb
module TextersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestTexter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/texters/_form.html.erb
<%= form_with(model: texter, local: true) do |form| %>
  <% if texter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(texter.errors.count, "error") %> prohibited this texter from being saved:</h2>

      <ul>
        <% texter.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :client_name %>
    <%= form.text_field :client_name %>
  </div>

  <div class="field">
    <%= form.label :message_description %>
    <%= form.text_area :message_description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/texters/edit.html.erb
<h1>Editing Texter</h1>

<%= render 'form', texter: @texter %>

<%= link_to 'Show', @texter %> |
<%= link_to 'Back', texters_path %>

app/views/texters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Texters</h1>

<table>
  <thead>
    <tr>
      <th>Client name</th>
      <th>Message description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @texters.each do |texter| %>
      <tr>
        <td><%= texter.client_name %></td>
        <td><%= texter.message_description %></td>
        <td><%= link_to 'Show', texter %></td>
        <td><%= link_to 'Edit', edit_texter_path(texter) %></td>
        <td><%= link_to 'Destroy', texter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Texter', new_texter_path %>

app/views/texters/new.html.erb
<h1>New Texter</h1>

<%= render 'form', texter: @texter %>

<%= link_to 'Back', texters_path %>

app/views/texters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Client name:</strong>
  <%= @texter.client_name %>
</p>

<p>
  <strong>Message description:</strong>
  <%= @texter.message_description %>
</p>

<%= link_to 'Edit', edit_texter_path(@texter) %> |
<%= link_to 'Back', texters_path %>